[book]
title = "gist-cache-rs Documentation"
description = "A CLI tool for efficiently caching, searching, and executing GitHub Gists"
authors = ["7rikazhexde"]
language = "en"
src = "book/src"

[build]
build-dir = "book/book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/7rikazhexde/gist-cache-rs"
edit-url-template = "https://github.com/7rikazhexde/gist-cache-rs/edit/main/{path}"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.print]
enable = true

[output.html.playground]
editable = false
copyable = true
copy-js = true
