[book]
authors = ["7rikazhexde"]
description = "A CLI tool for efficiently caching, searching, and executing GitHub Gists"
language = "en"
src = "book/src"
title = "gist-cache-rs Documentation"

[build]
build-dir = "book/book"

[output.html]
default-theme = "rust"
edit-url-template = "https://github.com/7rikazhexde/gist-cache-rs/edit/main/{path}"
git-repository-url = "https://github.com/7rikazhexde/gist-cache-rs"
preferred-dark-theme = "navy"

[output.html.fold]
enable = true
level = 1

[output.html.playground]
copy-js = true
copyable = true
editable = false

[output.html.print]
enable = true

[output.html.search]
boost-hierarchy = 1
boost-paragraph = 1
boost-title = 2
enable = true
expand = true
heading-split-level = 3
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
